### ISSUE TITLE
NanoPlot crash on openSUSE

### ISSUE THREAD

**Issue by gwaldbieser** [wdecoster/nanopack#5] opened 2018-03-10 18:46 UTC
Trying to upgrade nanopack on the openSUSE box 

$ cat /etc/*-release
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
openSUSE 42.3 (x86_64)
VERSION = 42.3
CODENAME = Malachite

$ python -V
Python 3.5.2 :: Anaconda custom (64-bit)
#########################################
NanoPlot ran but gave an error. 
I uninstalled nanopack, NanoPlot, NanoLyse, NanoComp, NanoFilt and NanoStat and started from scratch.
#########################################
$ pip install nanopack
Collecting nanopack
Collecting NanoStat>=0.6.1 (from nanopack)
Requirement already satisfied: NanoGUI in /root/anaconda3/lib/python3.5/site-packages (from nanopack)
Collecting NanoPlot>=0.20.1 (from nanopack)
Requirement already satisfied: nanoget>=0.15.0 in /root/anaconda3/lib/python3.5/site-packages (from nanopack)
Collecting NanoFilt>=1.5.2 (from nanopack)
Requirement already satisfied: nanomath>=0.13.3 in /root/anaconda3/lib/python3.5/site-packages (from nanopack)
Collecting NanoLyse>=0.2.1 (from nanopack)
Requirement already satisfied: nanoplotter>=0.16.5 in /root/anaconda3/lib/python3.5/site-packages (from nanopack)
Collecting NanoComp>=0.4.0 (from nanopack)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: scipy in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: python-dateutil in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: pysam>0.10.0.0 in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: seaborn in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: biopython in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: pandas>=0.22.0 in /root/anaconda3/lib/python3.5/site-packages (from NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: mappy>=2.2 in /root/anaconda3/lib/python3.5/site-packages (from NanoLyse>=0.2.1->nanopack)
Requirement already satisfied: matplotlib>=2.0.0 in /root/anaconda3/lib/python3.5/site-packages (from nanoplotter>=0.16.5->nanopack)
Requirement already satisfied: pauvre in /root/anaconda3/lib/python3.5/site-packages (from nanoplotter>=0.16.5->nanopack)
Requirement already satisfied: six>=1.5 in /root/anaconda3/lib/python3.5/site-packages (from python-dateutil->NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: pytz>=2011k in /root/anaconda3/lib/python3.5/site-packages (from pandas>=0.22.0->NanoPlot>=0.20.1->nanopack)
Requirement already satisfied: cycler>=0.10 in /root/anaconda3/lib/python3.5/site-packages (from matplotlib>=2.0.0->nanoplotter>=0.16.5->nanopack)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /root/anaconda3/lib/python3.5/site-packages (from matplotlib>=2.0.0->nanoplotter>=0.16.5->nanopack)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/anaconda3/lib/python3.5/site-packages (from matplotlib>=2.0.0->nanoplotter>=0.16.5->nanopack)
Requirement already satisfied: setuptools in /root/anaconda3/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.0->nanoplotter>=0.16.5->nanopack)
Installing collected packages: NanoStat, NanoPlot, NanoFilt, NanoLyse, NanoComp, nanopack
Successfully installed NanoComp-0.15.0 NanoFilt-2.0.1 NanoLyse-0.5.1 NanoPlot-1.10.5 NanoStat-1.1.0 nanopack-1.0.0
$ NanoComp -v
NanoComp 0.15.0
$ NanoPlot -v
NanoPlot 1.10.5
$ NanoLyse -v
NanoLyse 0.5.1
$ NanoFilt -v
NanoFilt 2.0.1
$ NanoStat -v
NanoStat 1.1.0
#######################################
##Ran Nanoplot on your test data
$ NanoPlot -t 32 --fastq reads.fastq.gz --N50 --loglength -o Plot1 &
[NanoPlot_20180310_1339.log](https://github.com/wdecoster/nanopack/files/1799683/NanoPlot_20180310_1339.log)

##These files are produced then it crashes.
HistogramReadlength.png
Log_LengthvsQualityScatterPlot_dot.png
LogTransformed_HistogramReadlength.png
NanoPlot_20180310_1339.log
NanoStats.txt
Weighted_HistogramReadlength.png
Weighted_LogTransformed_HistogramReadlength.png

#Log file
[NanoPlot_20180310_1339.log](https://github.com/wdecoster/nanopack/files/1799683/NanoPlot_20180310_1339.log)

**Comment by gwaldbieser** [comment] 2018-03-10 18:48
[NanoPlot_20180310_1339.log](https://github.com/wdecoster/nanopack/files/1799687/NanoPlot_20180310_1339.log)

**Comment by wdecoster** [comment] 2018-03-10 20:34
I believe this is a duplicate of https://github.com/wdecoster/NanoPlot/issues/21, can you confirm?

In my opinion this is a seaborn issue, and not NanoPlot itself. I will raise this on the seaborn github and see if they are willing to fix this, if not I shall fix it in NanoPlot.

Cheers, 
Wouter

**Comment by gwaldbieser** [comment] 2018-03-10 21:06
Looks like it. Thanks.

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Closed as completed** 2018-03-12 15:11 UTC
